<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R Stats Bootcamp - 12 ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./img/rstats-logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">12 ANOVA</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./" class="sidebar-logo-link">
      <img src="./img/rstats-logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Information</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">About</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link">Schedule</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Module 1: R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-setup.html" class="sidebar-item-text sidebar-link">1 Setup &amp; intro</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-r-lang.html" class="sidebar-item-text sidebar-link">2 R language</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-functions.html" class="sidebar-item-text sidebar-link">3 R Functions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-data.html" class="sidebar-item-text sidebar-link">4 Data objects</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-data-frames.html" class="sidebar-item-text sidebar-link">5 Data frames</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-data-manipulation.html" class="sidebar-item-text sidebar-link">6 Data subsetting</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Module 2: Stats</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-question-explore.html" class="sidebar-item-text sidebar-link">7 Explore data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-sampling-dist.html" class="sidebar-item-text sidebar-link">8 Distributions</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-correlation.html" class="sidebar-item-text sidebar-link">9 Correlation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression.html" class="sidebar-item-text sidebar-link">10 Regression</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-t-test.html" class="sidebar-item-text sidebar-link">11 T-test</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-1-way-anova.html" class="sidebar-item-text sidebar-link active">12 ANOVA</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#analysis-of-variance-anova" id="toc-analysis-of-variance-anova" class="nav-link active" data-scroll-target="#analysis-of-variance-anova">1 ANalysis Of VAriance (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">1.1 Objectives</a></li>
  </ul></li>
  <li><a href="#the-question-of-1-way-anova" id="toc-the-question-of-1-way-anova" class="nav-link" data-scroll-target="#the-question-of-1-way-anova">2 The question of 1-way ANOVA</a></li>
  <li><a href="#data-and-assumptions" id="toc-data-and-assumptions" class="nav-link" data-scroll-target="#data-and-assumptions">3 Data and assumptions</a>
  <ul class="collapse">
  <li><a href="#wide-format-data" id="toc-wide-format-data" class="nav-link" data-scroll-target="#wide-format-data">3.1 Wide format data</a></li>
  <li><a href="#long-format-data-preferred" id="toc-long-format-data-preferred" class="nav-link" data-scroll-target="#long-format-data-preferred">3.2 Long format data (preferred)</a></li>
  <li><a href="#formal-test-of-gaussian-residuals" id="toc-formal-test-of-gaussian-residuals" class="nav-link" data-scroll-target="#formal-test-of-gaussian-residuals">4.1 Formal test of Gaussian residuals</a></li>
  <li><a href="#homoscedasticity-check" id="toc-homoscedasticity-check" class="nav-link" data-scroll-target="#homoscedasticity-check">4.2 Homoscedasticity check</a></li>
  <li><a href="#bartlett-test" id="toc-bartlett-test" class="nav-link" data-scroll-target="#bartlett-test">4.3 Bartlett test</a></li>
  </ul></li>
  <li><a href="#graphing-anova" id="toc-graphing-anova" class="nav-link" data-scroll-target="#graphing-anova">5 Graphing ANOVA</a></li>
  <li><a href="#anova-f-test-statistic-and-alternatives" id="toc-anova-f-test-statistic-and-alternatives" class="nav-link" data-scroll-target="#anova-f-test-statistic-and-alternatives">6 ANOVA F test statistic and alternatives</a>
  <ul class="collapse">
  <li><a href="#perform-the-anova" id="toc-perform-the-anova" class="nav-link" data-scroll-target="#perform-the-anova">6.1 perform the ANOVA**</a></li>
  <li><a href="#anova-basic-output" id="toc-anova-basic-output" class="nav-link" data-scroll-target="#anova-basic-output">6.2 ANOVA basic output</a></li>
  <li><a href="#contrasts-and-post-hoc-test" id="toc-contrasts-and-post-hoc-test" class="nav-link" data-scroll-target="#contrasts-and-post-hoc-test">6.3 Contrasts and <em>post hoc</em> test</a></li>
  <li><a href="#post-hoc-tests" id="toc-post-hoc-tests" class="nav-link" data-scroll-target="#post-hoc-tests">6.4 <em>Post hoc</em> tests</a></li>
  <li><a href="#type-i-errors" id="toc-type-i-errors" class="nav-link" data-scroll-target="#type-i-errors">6.5 Type I errors</a></li>
  <li><a href="#tukey-hsd-honestly-significant-differences" id="toc-tukey-hsd-honestly-significant-differences" class="nav-link" data-scroll-target="#tukey-hsd-honestly-significant-differences">6.6 Tukey HSD (Honestly Significant Differences)</a></li>
  <li><a href="#alternatives-to-1-way-anova" id="toc-alternatives-to-1-way-anova" class="nav-link" data-scroll-target="#alternatives-to-1-way-anova">6.7 Alternatives to 1-way ANOVA</a></li>
  <li><a href="#kruskal-wallis-non-parametric-alternative-to-the-1-way-anova" id="toc-kruskal-wallis-non-parametric-alternative-to-the-1-way-anova" class="nav-link" data-scroll-target="#kruskal-wallis-non-parametric-alternative-to-the-1-way-anova">6.8 Kruskal-Wallis non-parametric alternative to the 1-way ANOVA</a></li>
  </ul></li>
  <li><a href="#anova-calculation-details" id="toc-anova-calculation-details" class="nav-link" data-scroll-target="#anova-calculation-details">7 ANOVA calculation details</a>
  <ul class="collapse">
  <li><a href="#anova-equations" id="toc-anova-equations" class="nav-link" data-scroll-target="#anova-equations">7.1 ANOVA Equations</a></li>
  <li><a href="#anova-variables" id="toc-anova-variables" class="nav-link" data-scroll-target="#anova-variables">7.2 ANOVA Variables</a></li>
  <li><a href="#anova-sources-of-variation-table" id="toc-anova-sources-of-variation-table" class="nav-link" data-scroll-target="#anova-sources-of-variation-table">7.3 ANOVA Sources of variation table</a></li>
  <li><a href="#do-an-anova-by-hand-programmatically" id="toc-do-an-anova-by-hand-programmatically" class="nav-link" data-scroll-target="#do-an-anova-by-hand-programmatically">7.4 Do an ANOVA “by hand” programmatically</a></li>
  </ul></li>
  <li><a href="#practice-exercises" id="toc-practice-exercises" class="nav-link" data-scroll-target="#practice-exercises">8 Practice exercises</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">8.1</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">8.2</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">8.3</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">8.4</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4">8.5</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5">8.6</a></li>
  </ul></li>
  <li><a href="#harper-adams-data-science" id="toc-harper-adams-data-science" class="nav-link" data-scroll-target="#harper-adams-data-science">Harper Adams Data Science</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">12 ANOVA</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/row.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">Arrange the arithmetic to compare more than two groups</figcaption><p></p>
</figure>
</div>
</center>
<p><br></p>
<section id="analysis-of-variance-anova" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance-anova">1 ANalysis Of VAriance (ANOVA)</h2>
<blockquote class="blockquote">
<p>The analysis of variance is not a mathematical theorem, but rather a convenient method of arranging the arithmetic. R. A. Fisher (via Wishart 1934. Sppl. J. Roy. Soc. 1(1):26-61.)</p>
</blockquote>
<p>Perhaps more so than any other tool, the Analysis of Variance (ANOVA) played a role in literally revolutionizing the idea of objectivity in using data to produce evidence to support claims for certain experimental designs. Invented by the famous statistician and biologist R. A. Fisher while he worked at Rothamsted Research, the intention was for ANOVA to be a useful tool to analyze agriculture experiments. Today, despite many innovations and competing approaches, it remains at the foundation of the basic practice of statistics.</p>
<p><br></p>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">1.1 Objectives</h3>
<ul>
<li><p>The question of 1-way ANOVA</p></li>
<li><p>Data and assumptions</p></li>
<li><p>Graphing</p></li>
<li><p>Test and alternatives</p></li>
<li><p>Practice exercises</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="the-question-of-1-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="the-question-of-1-way-anova">2 The question of 1-way ANOVA</h2>
<p>There are several reasons to use a “1-way ANOVA” experimental design. The scenario usually involves:</p>
<ul>
<li><p><strong>one numeric continuous dependent variable</strong> of interest</p></li>
<li><p><strong>a factor that contains 2 or more levels</strong>, often with a control</p></li>
<li><p>When there are just two levels, the 1-ANOVA is conceptually equivalent to the t-test</p></li>
</ul>
<p>An example might be something like a classic field trial, where crop pest damage is measured (the numeric continuous dependent variable) and the factor compares pest treatment with 3 levels: a control level (no pesticide), an organic pesticide, and a chemical pesticide. The basic question is whether there is an overall difference in the numeric dependent variable amongst the factor levels, however several kinds of questions are also possible to answer:</p>
<ul>
<li><p><strong>overall difference</strong> test of means between the factors</p></li>
<li><p>Comparison of difference of each factor level with the control or other reference factor level</p></li>
<li><p><strong><em>post hoc</em></strong> tests of difference between specific factor levels, e.g.&nbsp;pairwise tests for a factor with levels A, B, and C might test all possible comparisons A:B, A:C, and B:C.</p></li>
<li><p>Examination of the <strong>“sources of variation”</strong> observed in the dependent variable, e.g.&nbsp;what proportion of total variation can be accounted for by the factor</p></li>
</ul>
<p><br></p>
<p>The test statistic for ANOVA is the <strong>F ratio</strong>, which is proportion of variance in the dependent variable between the groups, relative to that within the categories. We will (very briefly) look at this calculation with the aim of gaining a practical understanding of what is going.</p>
<p><br></p>
</section>
<section id="data-and-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="data-and-assumptions">3 Data and assumptions</h2>
<p>The data we will look at is an experiment in animal genetics, looking at the weight of male chickens (8-week old weight in grams), where weight is the continuous dependent variable. The factor is the sire identity, where the measure young male chicks were sired by one of 5 sires, thus sire is a factor with 5 levels A, B, C, D, and E.</p>
<p><br></p>
<section id="wide-format-data" class="level3">
<h3 class="anchored" data-anchor-id="wide-format-data">3.1 Wide format data</h3>
<p>Here, the numeric data are stored in five vectors, each corresponding to one factor level. One row does not correspond to a single “case” because each column contains measures from different individual offspring. This is an unusual way to store data like this (these days), but we will look at this “wide format” first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data in "wide format" </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">687</span>, <span class="dv">691</span>, <span class="dv">793</span>, <span class="dv">675</span>, <span class="dv">700</span>, <span class="dv">753</span>, <span class="dv">704</span>, <span class="dv">717</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">618</span>, <span class="dv">680</span>, <span class="dv">592</span>, <span class="dv">683</span>, <span class="dv">631</span>, <span class="dv">691</span>, <span class="dv">694</span>, <span class="dv">732</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">618</span>, <span class="dv">687</span>, <span class="dv">763</span>, <span class="dv">747</span>, <span class="dv">687</span>, <span class="dv">737</span>, <span class="dv">731</span>, <span class="dv">603</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">600</span>, <span class="dv">657</span>, <span class="dv">669</span>, <span class="dv">606</span>, <span class="dv">718</span>, <span class="dv">693</span>, <span class="dv">669</span>, <span class="dv">648</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">717</span>, <span class="dv">658</span>, <span class="dv">674</span>, <span class="dv">611</span>, <span class="dv">678</span>, <span class="dv">788</span>, <span class="dv">650</span>, <span class="dv">690</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chicken.wide <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(A, B, C, D, E))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    A   B   C   D   E
1 687 618 618 600 717
2 691 680 687 657 658
3 793 592 763 669 674
4 675 683 747 606 611
5 700 631 687 718 678
6 753 691 737 693 788</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="long-format-data-preferred" class="level3">
<h3 class="anchored" data-anchor-id="long-format-data-preferred">3.2 Long format data (preferred)</h3>
<p>Here, the numeric data is stored in a single vector, with a factor vector for the sire data. Each row corresponds to a single, independent “case”. This format is preferred and adheres to the “Tidy Data” standard, although it is not hard to move between wide and long formats.</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data in "wide format"  ####</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">687</span>, <span class="dv">691</span>, <span class="dv">793</span>, <span class="dv">675</span>, <span class="dv">700</span>, <span class="dv">753</span>, <span class="dv">704</span>, <span class="dv">717</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">618</span>, <span class="dv">680</span>, <span class="dv">592</span>, <span class="dv">683</span>, <span class="dv">631</span>, <span class="dv">691</span>, <span class="dv">694</span>, <span class="dv">732</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">618</span>, <span class="dv">687</span>, <span class="dv">763</span>, <span class="dv">747</span>, <span class="dv">687</span>, <span class="dv">737</span>, <span class="dv">731</span>, <span class="dv">603</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">600</span>, <span class="dv">657</span>, <span class="dv">669</span>, <span class="dv">606</span>, <span class="dv">718</span>, <span class="dv">693</span>, <span class="dv">669</span>, <span class="dv">648</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">717</span>, <span class="dv">658</span>, <span class="dv">674</span>, <span class="dv">611</span>, <span class="dv">678</span>, <span class="dv">788</span>, <span class="dv">650</span>, <span class="dv">690</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chicken.wide <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(A, B, C, D, E))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    A   B   C   D   E
1 687 618 618 600 717
2 691 680 687 657 658
3 793 592 763 669 674
4 675 683 747 606 611
5 700 631 687 718 678
6 753 691 737 693 788</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data in "long format"  ####</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The hard way</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>weight <span class="ot">&lt;-</span> <span class="fu">c</span>(A,B,C,D,E)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>sire <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"A"</span>, <span class="dv">8</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">rep</span>(<span class="st">"B"</span>, <span class="dv">8</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">rep</span>(<span class="st">"C"</span>, <span class="dv">8</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">rep</span>(<span class="st">"D"</span>, <span class="dv">8</span>),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>          <span class="fu">rep</span>(<span class="st">"E"</span>, <span class="dv">8</span>) )</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(weight, sire))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  weight sire
1    687    A
2    691    A
3    793    A
4    675    A
5    700    A
6    753    A</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">data.frame</span>(weight, sire))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   weight sire
35    674    E
36    611    E
37    678    E
38    788    E
39    650    E
40    690    E</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The "programm-ey" way</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>weight1 <span class="ot">&lt;-</span> <span class="fu">c</span>(A,B,C,D,E)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>sire1 <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">"character"</span>, <span class="at">length =</span> <span class="dv">40</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) { sire1[(<span class="dv">8</span><span class="sc">*</span>i<span class="dv">-8</span>)<span class="sc">+</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)] <span class="ot">&lt;-</span> <span class="fu">rep</span>(LETTERS[i], <span class="dv">8</span>) }</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(weight1, sire1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  weight1 sire1
1     687     A
2     691     A
3     793     A
4     675     A
5     700     A
6     753     A</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">data.frame</span>(weight1, sire1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   weight1 sire1
35     674     E
36     611     E
37     678     E
38     788     E
39     650     E
40     690     E</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With function from {tidyr}</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chicken.wide) <span class="co"># From above</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    A   B   C   D   E
1 687 618 618 600 717
2 691 680 687 657 658
3 793 592 763 669 674
4 675 683 747 606 611
5 700 631 687 718 678
6 753 691 737 693 788</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2) <span class="co"># For melt()</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#?melt</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>new.long <span class="ot">&lt;-</span> <span class="fu">melt</span>(chicken.wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>No id variables; using all as measure variables</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(new.long) <span class="co"># Not bad but note the variable names... </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  variable value
1        A   687
2        A   691
3        A   793
4        A   675
5        A   700
6        A   753</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(new.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "variable" "value"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flash challenge: change the variable names in new.long</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(new.long) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Sire'</span>, <span class="st">'Weight'</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(new.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sire"   "Weight"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NB, you should probably just use long format for your data in the first place!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>R output</code></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">head</span>(new.long) <span class="co"># Not bad but note the variable names</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  variable value</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>        A   <span class="dv">687</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span>        A   <span class="dv">691</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span>        A   <span class="dv">793</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span>        A   <span class="dv">675</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span>        A   <span class="dv">700</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="dv">6</span>        A   <span class="dv">753</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p>
<p>##4 Assumptions of ANOVA</p>
<p>The assumptions of ANOVA are similar to those of regression (indeed, both are a specific kind of Linear Model and share the assumptions of the Gaussian Linear Model). The most important to consider now are:</p>
<ul>
<li><p>Gaussian residuals (we test graphically and with NHST for Gaussian residual distribution)</p></li>
<li><p>Homoscedasticity (we test graphically with a residuals versus fitted values plot)</p></li>
<li><p>Equality of variance (plot of residual versus factor and NHST for == variance)</p></li>
<li><p>Independent observations (we assume this for now with the chicken data, but will not test is formally)</p></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## **Assumptions** ####</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="do">## - Gaussian residuals ####</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the model object with aov()</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ?aov</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> Sire, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> new.long)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph to examine Gaussian assumption of residuals</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># NB we use rstandard()</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">rstandard</span>(m1),</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Gaussian?"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at residuals with qqPlot()</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># For qqPlot()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(<span class="at">x =</span> m1,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Gaussian?"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24 38</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="formal-test-of-gaussian-residuals" class="level3">
<h3 class="anchored" data-anchor-id="formal-test-of-gaussian-residuals">4.1 Formal test of Gaussian residuals</h3>
<p>At a glance, there are no serious issues with the assumption of Gaussian residual distribution. We can use NHST to help us decide; we will try the <code>shapiro.test()</code>.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">rstandard</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rstandard(m1)
W = 0.99182, p-value = 0.9913</code></pre>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>There is no evidence of difference to Gaussian in our residuals for our ANOVA model (Shapiro-Wilk: W = 0.99, n = 40, P = 0.99).</p>
</blockquote>
<p><br></p>
</section>
<section id="homoscedasticity-check" class="level3">
<h3 class="anchored" data-anchor-id="homoscedasticity-check">4.2 Homoscedasticity check</h3>
<p>We will look at the residuals relative to the fitted values.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for homoscedasticity check</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">formula =</span> <span class="fu">rstandard</span>(m1) <span class="sc">~</span> <span class="fu">fitted</span>(m1),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"m1: residuals"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"m1: fitted values"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Spread similar across x?"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the mean residual y points (just to check)</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">rstandard</span>(m1), <span class="at">by =</span> <span class="fu">list</span>(new.long<span class="sc">$</span>Sire), <span class="at">FUN =</span> mean)[,<span class="dv">2</span>]</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the x unique fitted values (just to check)</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">round</span>(<span class="fu">fitted</span>(m1), <span class="dv">6</span>))</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y1, </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">1.2</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
</section>
<section id="bartlett-test" class="level3">
<h3 class="anchored" data-anchor-id="bartlett-test">4.3 Bartlett test</h3>
<p>Finally, we can use NHST just to have a final check of whether the variance in weight is equal between factor levels. There are several ways to do this; we will use the Bartlett test using <code>bartlett.test()</code>, which compares the variance for more than 2 groups.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NHST to examine  assumption of homoscedasticity</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (homoscedasticiyy good, heteroscedasticity bad)</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(<span class="at">formula =</span> weight<span class="sc">~</span>sire, <span class="at">data =</span> new.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  weight by sire
Bartlett's K-squared = 1.6868, df = 4, p-value = 0.7931</code></pre>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>We find no evidence that variance in offspring weight differs between sires (Bartlett test: K-sqared = 1.69, df = 4, P = 0.79).</p>
</blockquote>
<p><br></p>
</section>
</section>
<section id="graphing-anova" class="level2">
<h2 class="anchored" data-anchor-id="graphing-anova">5 Graphing ANOVA</h2>
<p>The classic way to visualize the 1-way ANOVA is with boxplot, with some way to show the central tendency of the data separately for each factor level. For continuous variables, boxplots show this perfectly. For count variables, barplots are sometimes used with the height set to the mean, along with some form of error bar. Here we will use a boxplot.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## basic boxplot ####</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># It always pays to make a nice plot</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Do you think sire affects offspring weight?</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Weight <span class="sc">~</span> Sire, <span class="at">data =</span> new.long, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Is this plot good enough?"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>So, it looks like sire identity <em>could</em> have an effect on mean male offspring weight. But, is this graph good enough? Can we make it better? Let’s critique it:</p>
<ul>
<li><p>(important) The y axis does not indicate the unit of measurement</p></li>
<li><p>(important) Neither axis title is capitalized</p></li>
<li><p>(optional) Adding on the points might add interesting detail</p></li>
<li><p>(optional) Reference line for control (we do not really have a control here) or of the “grand mean” might be useful</p></li>
</ul>
<p><br></p>
<p>5.1 Make a better graph</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">## **Make a better graph** ####</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Weight <span class="sc">~</span> Sire, <span class="at">data =</span> new.long,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Weight (g)"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Sire"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Effect of Sire on 8-wk weight"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex =</span> <span class="dv">0</span>) <span class="co"># Get rid of the outlier dot (we will draw it back)</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Make horizontal line for grand mean</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(new.long<span class="sc">$</span>Weight), </span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>) <span class="co"># Mere vanity</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw on raw data</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> <span class="fu">jitter</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">each =</span> <span class="dv">8</span>), <span class="at">amount =</span> .<span class="dv">1</span>),</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> new.long<span class="sc">$</span>Weight,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> .<span class="dv">8</span>, <span class="at">col =</span> <span class="st">"blue"</span>) <span class="co"># Mere vanity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
</section>
<section id="anova-f-test-statistic-and-alternatives" class="level2">
<h2 class="anchored" data-anchor-id="anova-f-test-statistic-and-alternatives">6 ANOVA F test statistic and alternatives</h2>
<p>The basic application of ANOVA in <code>R</code> is the <code>aov()</code> function. There are actually a lot of alternative ways to perform the exact same test in <code>R</code>.</p>
<p>To micro-digress, ANOVA is a subset of the Gaussian linear model; the Gaussian linear model is a subset of the General Linear Model; and the General Linear Model is a subset of the GeneralIZED Linear Model. For now we will forget all of that and go with <code>aov()</code>.</p>
<p><br></p>
<section id="perform-the-anova" class="level3">
<h3 class="anchored" data-anchor-id="perform-the-anova">6.1 perform the ANOVA**</h3>
<p>We have a few things to do here:</p>
<ul>
<li><p>Perform 1-way ANOVA and look at the basic output for the <strong>overall effect of sire</strong></p></li>
<li><p>Look at how to examine <strong>contrasts</strong> (differences between the control or a reference factor level, and each of the others) and <strong><em>post hoc</em></strong> testing (e.g.&nbsp;all pairwise comparisons between factor levels)</p></li>
<li><p>Examine what happens in the ANOVA in a little more detail</p></li>
</ul>
<p><br></p>
</section>
<section id="anova-basic-output" class="level3">
<h3 class="anchored" data-anchor-id="anova-basic-output">6.2 ANOVA basic output</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Perform 1-way ANOVA ####</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># NB if the factor is a character, it "should" be coerced to a factor</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># by R, "the passive aggressive butler"</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># If in doubt, explicitly make the vector class == factor()</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> <span class="fu">factor</span>(Sire), </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> new.long)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
factor(Sire)  4  17426    4356   1.872  0.137
Residuals    35  81442    2327               </code></pre>
</div>
</div>
<p><br></p>
<p>The output is formatted in a classic “ANOVA Table” style. There are 2 rows - one for the “main effect” of the sire factor, one for the residual error. The test statistic is the F value (1.87), the P-value column is named “Pr(&gt;F)” (0.14), and there are 4 degrees of freedom for this test for the factor (the factor degrees of freedom is the number of factor levels minus 1 = 5 factor levels - 1 = 4; the residual degrees of freedom is the total number of observations minus the number of factor levels = 40 - 5 = 35).</p>
<blockquote class="blockquote">
<p>Here we can see that the overall effect of sire does not significantly explain variation in weight (1-way ANOVA: F = 1.87, df = 4,35, P = 0.14).</p>
</blockquote>
<p><br></p>
</section>
<section id="contrasts-and-post-hoc-test" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-and-post-hoc-test">6.3 Contrasts and <em>post hoc</em> test</h3>
<p>An alternative to the ANOVA table format, and possibly different to the question of an overall mean effect of the factor, is the approach for a regular linear model looking at differences for each factor level relative to a reference factor level like a control. For our experiment, let’s say that sire C is our reference level sire, against which we would like to statistically compare offspring weight for other sires.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lm() and summary() to generate contrasts</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use relevel() to set sire C to the reference factor level</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make Sire C the reference level</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>new.long<span class="sc">$</span>Sire <span class="ot">&lt;-</span> <span class="fu">relevel</span>(new.long<span class="sc">$</span>Sire, <span class="at">ref=</span><span class="st">"C"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate linear model</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> Sire, </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> new.long)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weight ~ Sire, data = new.long)

Residuals:
    Min      1Q  Median      3Q     Max 
-93.625 -29.312  -2.875  33.906 104.750 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   696.63      17.05  40.846   &lt;2e-16 ***
SireA          18.38      24.12   0.762    0.451    
SireB         -31.50      24.12  -1.306    0.200    
SireD         -39.13      24.12  -1.622    0.114    
SireE         -13.38      24.12  -0.555    0.583    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 48.24 on 35 degrees of freedom
Multiple R-squared:  0.1763,    Adjusted R-squared:  0.08211 
F-statistic: 1.872 on 4 and 35 DF,  p-value: 0.1373</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Weight <span class="sc">~</span> Sire, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> new.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><code>R output</code></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> Sire, </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>          <span class="at">data =</span> new.long)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m2)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>Call<span class="sc">:</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> Sire, <span class="at">data =</span> new.long)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>Residuals<span class="sc">:</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    Min      1Q  Median      3Q     Max </span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">93.625</span> <span class="sc">-</span><span class="fl">29.312</span>  <span class="sc">-</span><span class="fl">2.875</span>  <span class="fl">33.906</span> <span class="fl">104.750</span> </span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>Coefficients<span class="sc">:</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error t value <span class="fu">Pr</span>(<span class="sc">&gt;</span><span class="er">|</span>t<span class="sc">|</span>)    </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>(Intercept)   <span class="fl">696.63</span>      <span class="fl">17.05</span>  <span class="fl">40.846</span>   <span class="sc">&lt;</span><span class="fl">2e-16</span> <span class="sc">**</span><span class="er">*</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>SireA          <span class="fl">18.38</span>      <span class="fl">24.12</span>   <span class="fl">0.762</span>    <span class="fl">0.451</span>    </span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>SireB         <span class="sc">-</span><span class="fl">31.50</span>      <span class="fl">24.12</span>  <span class="sc">-</span><span class="fl">1.306</span>    <span class="fl">0.200</span>    </span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>SireD         <span class="sc">-</span><span class="fl">39.13</span>      <span class="fl">24.12</span>  <span class="sc">-</span><span class="fl">1.622</span>    <span class="fl">0.114</span>    </span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>SireE         <span class="sc">-</span><span class="fl">13.38</span>      <span class="fl">24.12</span>  <span class="sc">-</span><span class="fl">0.555</span>    <span class="fl">0.583</span>    </span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>Signif. codes<span class="sc">:</span>  <span class="dv">0</span> <span class="st">'***'</span> <span class="fl">0.001</span> <span class="st">'**'</span> <span class="fl">0.01</span> <span class="st">'*'</span> <span class="fl">0.05</span> <span class="st">'.'</span> <span class="fl">0.1</span> <span class="st">' '</span> <span class="dv">1</span></span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>Residual standard error<span class="sc">:</span> <span class="fl">48.24</span> on <span class="dv">35</span> degrees of freedom</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>Multiple R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.1763</span>,    Adjusted R<span class="sc">-</span>squared<span class="sc">:</span>  <span class="fl">0.08211</span> </span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>F<span class="sc">-</span>statistic<span class="sc">:</span> <span class="fl">1.872</span> on <span class="dv">4</span> and <span class="dv">35</span> DF,  p<span class="sc">-</span>value<span class="sc">:</span> <span class="fl">0.1373</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p>
<p>Notice how the output format has changed. This is because the summary function (and lots of functions in fact) “behave differently” in response to the specific <code>class()</code> of object we pass to it (here an <code>lm</code> object; before an <code>aov</code> object). One big difference we see is the table of contrasts. Now, there is are 5 rows: one for the intercept coefficient (testing whether the “grand mean” of Weight is different to zero - NB this is not at all interesting for us), and for rows comparing each factor level to the reference mean for sire “C”.</p>
<p>Here, the Estimate column is an estimate of the AMOUNT of difference in weight relative to the reference mean weight for that sire. E.g., sire B offspring weight is estimated at -31.5 grams (the negative indicate less than) compared to offspring weight for sire C. However, this observed sample difference is not statistically significant (P = 0.20).</p>
<p>Notice the overall F value and p-value for the 1-way are also present at the bottom of the output, which is exactly the same as that produced by the <code>aov()</code> function.</p>
<p><br></p>
<p>We can make a new boxplot based on our new sire variable and notice how it automatically moves sire C to the leftmost “reference position”</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Weight <span class="sc">~</span> Sire, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> new.long,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Sire C as reference"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="post-hoc-tests" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-tests">6.4 <em>Post hoc</em> tests</h3>
<blockquote class="blockquote">
<p>The collection and analysis of data should be driven by the question. We should always be careful to make the distinction between data analysis that <strong>SHOULD be done</strong> versus that which merely <strong>CAN be done</strong>. The former is driven by prediction and motivated by evidence, expectation and the design of data collection. The latter is often a waste of time, or worse, a “fishing expedition” in crass pursuit of a P-value, any P-value, which is &lt; 0.05 .</p>
</blockquote>
<p><br></p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://imgs.xkcd.com/comics/significant.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">The meaning of significance</figcaption><p></p>
</figure>
</div>
</center>
<p><br></p>
<p><em>Post hoc</em> tests are often interesting in research, and the 1-way ANOVA is a good example, where an overall question of “is there a difference?” can be enhanced by asking whether there are particular or specific differences, say between pairs of means. The phrase <em>post hoc</em> implies that the sometimes these questions can be an afterthought. Thus, consideration should be given as to whether these specific questions NEED to be asked.</p>
<p><br></p>
</section>
<section id="type-i-errors" class="level3">
<h3 class="anchored" data-anchor-id="type-i-errors">6.5 Type I errors</h3>
<p>The alpha (<span class="math inline">\(\alpha\)</span>) value, the value to which we compare our P-value, can be interpreted as the (maximum) probability we are willing to accept of being wrong if we conclude there is significance in our data. Traditionally, this alpha value is accepted to be 0.05, or a 5% chance of making a false positive error. When multiple tests are made on the same data, it increases the chance of discovering a false positive, by chance alone, to above 5%. Thus, there are methods that are used to avoid doing this, by adjusting the P-value to keep the overall likelihood of false positive error at 5%.</p>
<p>The <strong>Bonferroni adjustment</strong> <a href="https://www.bmj.com/content/310/6973/170.short">see Bland and Altman 1995</a> is a baseline, conservative adjustment to the alpha value to avoid false positive errors. This might be typically applied to a 1-way ANOVA situation where specific, pairwise comparisons between means are required that are not covered by the overall test, or by the contrasts. E.g. in our chicken data, we know there is not a difference in offspring weight between sire C and all other sire offsring weights: C:A, C:B, C:D, C:E, but what if we really wanted to test the others? We could use the <strong>Bonferroni adjustment</strong> as implemented in the <code>pairwise.t.test()</code> function.</p>
<p>The <strong>Bonferroni adjustment</strong> simply divides the alpha expected value by the number of <em>post hoc</em> pairwise comparisons. NB the Bonferroni adjustment is conservative, and there are alternatives. The point here is just to illustrate how these tests function and, like with many things, more study will be required to round out foundational knowledge for <em>post hoc</em> testing procedures. The Bonferroni test is nice to know about and understand because it is easy to use, and manually calculate, and can be applied to any situation.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this:</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Bonferroni ####</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ?pairwise.t.test</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># there are a few p.adjust.methods</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co"># c("holm", "hochberg", "hommel", "bonferroni", "BH", "BY",</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   "fdr", "none")</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># we will use "bonferroni"</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> new.long<span class="sc">$</span>Weight, </span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">g =</span> new.long<span class="sc">$</span>Sire,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  new.long$Weight and new.long$Sire 

  C    A    B    D   
A 1.00 -    -    -   
B 1.00 0.46 -    -   
D 1.00 0.23 1.00 -   
E 1.00 1.00 1.00 1.00

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p><br></p>
<p>NB the output here is a matrix of (Bonferroni adjusted!) p-values for each possible pairwise comparison (none are significant, i.e., less than 0.05). It is also possible to simply calculate uncorrected p-values and compare them to Bonferroni adjust alpha values, as described above!</p>
<p><br></p>
</section>
<section id="tukey-hsd-honestly-significant-differences" class="level3">
<h3 class="anchored" data-anchor-id="tukey-hsd-honestly-significant-differences">6.6 Tukey HSD (Honestly Significant Differences)</h3>
<p>The Tukey HSD test is ideal for 1-way ANOVA, and is less conservative than the Bonferroni adjustment. We use the <code>Tukey.HSD()</code> function to apply it here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Tukey Honestly Significant Differences ####</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ?TukeyHSD</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(m1) <span class="co"># NB m1 - this function requires an "aov" object</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Weight ~ factor(Sire), data = new.long)

$`factor(Sire)`
       diff        lwr       upr     p adj
B-A -49.875 -119.21883  19.46883 0.2565333
C-A -18.375  -87.71883  50.96883 0.9397600
D-A -57.500 -126.84383  11.84383 0.1436866
E-A -31.750 -101.09383  37.59383 0.6830523
C-B  31.500  -37.84383 100.84383 0.6893101
D-B  -7.625  -76.96883  61.71883 0.9977281
E-B  18.125  -51.21883  87.46883 0.9425341
D-C -39.125 -108.46883  30.21883 0.4937665
E-C -13.375  -82.71883  55.96883 0.9806452
E-D  25.750  -43.59383  95.09383 0.8216369</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-1-way-anova_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br></p>
<p>Notice the table of pairwise comparisons. The format is slightly different than that for the simple <code>pairwise.t.test()</code> function output and there is a bit more information. Also note that the p-values tend to be smaller for the exact same comparisons, but there are sill no significant comparisons.</p>
<p><br></p>
</section>
<section id="alternatives-to-1-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="alternatives-to-1-way-anova">6.7 Alternatives to 1-way ANOVA</h3>
<p>In case the assumptions of 1-way ANOVA cannot be met by the data, there are a few options:</p>
<ul>
<li><p>Attempt to transform the data (e.g.&nbsp;with <code>log()</code>, <code>sqrt()</code> or other transformation) to “coerce” the data to conform to the assumptions of 1-way ANOVA</p></li>
<li><p>Use an alternative test for which assumptions are not violated</p></li>
</ul>
<p><br></p>
<p>The simplest alternative test to use for a 1-way ANOVA design would be a “non-parameteric” test that simply does not make the assumptions of Gaussian residuals or of homscedasticity. NB there are other many other methods as well (e.g.&nbsp;the Generalized linear model, randomization, Bayesian modelling), which we will not cover here.</p>
<p>Non-parametric tests have the advantage of being very easy to use, and being very easy to interpret as they tend to be analogous to tests that require assumptions of the data (so-called “parametric tests” like the t-test, regression and 1-way ANOVA).</p>
<p>A downside to these non-parametric tests is that they tend to have less <strong>statistical power</strong>. That is, they are less likely than their parametric cousins to detect a significant difference even if one does exist!</p>
<p><br></p>
</section>
<section id="kruskal-wallis-non-parametric-alternative-to-the-1-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="kruskal-wallis-non-parametric-alternative-to-the-1-way-anova">6.8 Kruskal-Wallis non-parametric alternative to the 1-way ANOVA</h3>
<p>Here we will look at a non-parametric test that is perfect to use instead of, the Kruskal-Wallis test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this:</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ?kruskal.test</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(<span class="at">formula =</span> Weight <span class="sc">~</span> Sire,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> new.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Weight by Sire
Kruskal-Wallis chi-squared = 7.648, df = 4, p-value = 0.1054</code></pre>
</div>
</div>
<p><br></p>
<p>The result is qualitatively the same as that for our 1-way ANOVA test, which is not surprising. Reporting the results of this test is similar as well.</p>
<p><br></p>
<blockquote class="blockquote">
<p>We found no evidence of a difference in offspring weight for different sires (Kruskal-Wallis: chi-squared = 7.65, df = 4, P = 0.11).</p>
</blockquote>
<p><br></p>
</section>
</section>
<section id="anova-calculation-details" class="level2">
<h2 class="anchored" data-anchor-id="anova-calculation-details">7 ANOVA calculation details</h2>
<div class="sourceCode" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our data</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>chicken.wide</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p>
<section id="anova-equations" class="level3">
<h3 class="anchored" data-anchor-id="anova-equations">7.1 ANOVA Equations</h3>
<p><img src="img/2.6-anova-equations.png" class="img-fluid">{width = “600px”}</p>
<p><br></p>
</section>
<section id="anova-variables" class="level3">
<h3 class="anchored" data-anchor-id="anova-variables">7.2 ANOVA Variables</h3>
<p><img src="img/2.6-anova-variables.png" class="img-fluid">{width = “400px”}</p>
<p><br></p>
</section>
<section id="anova-sources-of-variation-table" class="level3">
<h3 class="anchored" data-anchor-id="anova-sources-of-variation-table">7.3 ANOVA Sources of variation table</h3>
<p><img src="img/2.6-anova-sov.png" class="img-fluid"></p>
<p><br></p>
<blockquote class="blockquote">
<p>I like the cocksure argument that you never need to actually “do an ANOVA by hand” because we have computers for that sort of thing these days. Which, we do. But, I think I would make a distinction between someone who has never, or fears they cannot, calculate an ANOVA, versus someone who might occasionally do so just to understand better how the world works. I know which one I would rather be.</p>
</blockquote>
<blockquote class="blockquote">
<p>- Unknown philosopher</p>
</blockquote>
<p><br></p>
</section>
<section id="do-an-anova-by-hand-programmatically" class="level3">
<h3 class="anchored" data-anchor-id="do-an-anova-by-hand-programmatically">7.4 Do an ANOVA “by hand” programmatically</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ANOVA details ####</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this:</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For the code below, try to follow what is going on in the code</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># It is okay if not every detail is clear yet</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Do we get the same answer as aov()?</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>n.groups <span class="ot">&lt;-</span> <span class="fu">ncol</span>(chicken.wide)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>n.per.group <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">"integer"</span>, <span class="at">length =</span> <span class="fu">ncol</span>(chicken.wide))</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(chicken.wide)) {n.per.group[i] <span class="ot">&lt;-</span> <span class="fu">length</span>(chicken.wide[,i])}</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>n.individuals <span class="ot">&lt;-</span> <span class="fu">ncol</span>(chicken.wide)<span class="sc">*</span><span class="fu">nrow</span>(chicken.wide)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>df.between <span class="ot">&lt;-</span> n.groups <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>df.within <span class="ot">&lt;-</span> n.individuals <span class="sc">-</span> n.groups</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>mean.total <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">as.matrix</span>(chicken.wide))</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>mean.per.group <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(chicken.wide)</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>ss.between <span class="ot">&lt;-</span> <span class="fu">sum</span>(n.per.group<span class="sc">*</span>(mean.per.group <span class="sc">-</span> mean.total)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>ss.within <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sum</span>((chicken.wide[,<span class="dv">1</span>] <span class="sc">-</span> mean.per.group[<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">sum</span>((chicken.wide[,<span class="dv">2</span>] <span class="sc">-</span> mean.per.group[<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">sum</span>((chicken.wide[,<span class="dv">3</span>] <span class="sc">-</span> mean.per.group[<span class="dv">3</span>])<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">sum</span>((chicken.wide[,<span class="dv">4</span>] <span class="sc">-</span> mean.per.group[<span class="dv">4</span>])<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">sum</span>((chicken.wide[,<span class="dv">5</span>] <span class="sc">-</span> mean.per.group[<span class="dv">5</span>])<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>                 )</span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>ms.between <span class="ot">&lt;-</span> ss.between<span class="sc">/</span>df.between</span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a>ms.within <span class="ot">&lt;-</span> ss.within<span class="sc">/</span>df.within</span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Manual F</span></span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a>(myF <span class="ot">&lt;-</span> ms.between<span class="sc">/</span>ms.within)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.872189</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anova table</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)<span class="sc">$</span><span class="st">"F value"</span>[<span class="dv">1</span>] <span class="co"># Store-bought F</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.872189</code></pre>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="practice-exercises" class="level2">
<h2 class="anchored" data-anchor-id="practice-exercises">8 Practice exercises</h2>
<p>For these exercises, run the code below to recreate the data object <code>pest</code>. There are 40 rows and 2 variables with 2 variables: <code>damage</code> and <code>treatment</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pest <span class="ot">&lt;-</span> <span class="fu">structure</span>(<span class="fu">list</span>(<span class="at">damage =</span> <span class="fu">c</span>(<span class="fl">113.7</span>, <span class="fl">94.4</span>, <span class="fl">103.6</span>, </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="fl">106.3</span>, <span class="dv">104</span>, <span class="fl">98.9</span>, </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">115.1</span>, <span class="fl">99.1</span>, <span class="fl">120.2</span>, <span class="fl">99.4</span>, </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                          <span class="dv">88</span>, <span class="fl">97.9</span>, <span class="fl">61.1</span>, <span class="fl">72.2</span>, <span class="fl">73.7</span>, </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">81.4</span>, <span class="fl">72.2</span>, <span class="fl">48.4</span>, <span class="fl">50.6</span>, <span class="fl">88.2</span>, </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">46.9</span>, <span class="fl">32.2</span>, <span class="fl">48.3</span>, <span class="fl">62.1</span>, <span class="dv">69</span>, </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">45.7</span>, <span class="fl">47.4</span>, <span class="fl">32.4</span>, <span class="fl">54.6</span>, <span class="fl">43.6</span>, </span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">104.6</span>, <span class="dv">107</span>, <span class="fl">110.4</span>, <span class="fl">93.9</span>, <span class="dv">105</span>, </span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">82.8</span>, <span class="fl">92.2</span>, <span class="fl">91.5</span>, <span class="fl">75.9</span>, <span class="fl">100.4</span>), </span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">treatment =</span> <span class="fu">c</span>(<span class="st">"control"</span>, <span class="st">"control"</span>, </span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"control"</span>, <span class="st">"control"</span>,</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"control"</span>, <span class="st">"control"</span>, </span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"control"</span>, <span class="st">"control"</span>, </span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"control"</span>, <span class="st">"control"</span>,</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.half"</span>, <span class="st">"x.half"</span>, </span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.half"</span>, <span class="st">"x.half"</span>, </span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.half"</span>, <span class="st">"x.half"</span>, </span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.half"</span>, <span class="st">"x.half"</span>, </span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.half"</span>, <span class="st">"x.half"</span>, </span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.full"</span>, <span class="st">"x.full"</span>, </span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.full"</span>, <span class="st">"x.full"</span>,</span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.full"</span>, <span class="st">"x.full"</span>, </span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.full"</span>, <span class="st">"x.full"</span>, </span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"x.full"</span>, <span class="st">"x.full"</span>, </span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"organic"</span>, <span class="st">"organic"</span>, </span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"organic"</span>, <span class="st">"organic"</span>, </span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"organic"</span>, <span class="st">"organic"</span>, </span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"organic"</span>, <span class="st">"organic"</span>, </span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"organic"</span>, <span class="st">"organic"</span>)), </span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a>                  <span class="at">class =</span> <span class="st">"data.frame"</span>, </span>
<span id="cb56-31"><a href="#cb56-31" aria-hidden="true" tabindex="-1"></a>                  <span class="at">row.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="sc">-</span>40L))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>Think of this data as the result of an experiment looking at the effectiveness of pesticide treatment on leaf damage. Let us imagine that this experiment measured leaf damage (variable “damage” measured in mm squared) and that the plants were treated with one of 4 treatment levels:</p>
<p>Variable <code>treatment</code> with levels</p>
<ul>
<li><p><code>control</code></p></li>
<li><p><code>x.half</code></p></li>
<li><p><code>x.full</code></p></li>
<li><p><code>organic</code></p></li>
</ul>
<p>The experiment is of course designed to look at an overall effect the various treatments may have to reduce leaf damage relative to the <code>control.</code> In addition, it is of interest to examine the effect of the <code>organic</code> treatment compared to that of the <code>x.half</code> to the <code>x.full.</code></p>
<p>The experiment ran using 40 potted plants spaced 1m from each other in a greenhouse setting. Each treatment was randomly assigned to 10 plants. Onto each plant was placed 5 red lily beetle (<em>Lilioceris lilii</em>) pairs.</p>
<p><br></p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/2.6-red-lily-beetle.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Red lily beetle</figcaption><p></p>
</figure>
</div>
</center>
<p><br></p>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">8.1</h3>
<p>Make a good, appropriate graph representing the overall experiment. Show your code. Describe any trends in the data that are apparent from the graph, as well as an initial assessment of principle assumptions of 1-way ANOVA based only on your single graph.</p>
<p><br></p>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">8.2</h3>
<p>Test the assumption of Gaussian residuals for 1-way ANOVA using any graphs or NHST approach that you deem appropriate. Show your code and briefly describe your EDA findings and conclusion as to whether these data adhere to the Gaussian assumption.</p>
<p><br></p>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">8.3</h3>
<p>Test the assumption of homoscedasticity of residuals for 1-way ANOVA using any graphs or NHST approach that you deem appropriate. Show your code and briefly describe your EDA findings and conclusion as to whether these data adhere to the homoscedasticity assumption.</p>
<p><br></p>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">8.4</h3>
<p>Perform either a 1-way ANOVA or an appropriate alternative based on your findings in the previous answers. Show your code, state your results in the technical style and briefly interpret your findings.</p>
<p><br></p>
</section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4">8.5</h3>
<p>Perform an appropriate set of <em>post hoc</em> tests to compare pairwise mean differences in these data. Focus on the <em>post hoc</em> questions of interest: Is the organic pesticide effective? Does dose matter in the non-organic treatments?</p>
<p><br></p>
</section>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5">8.6</h3>
<p>Write a plausible practice question involving any aspect of data handling, graphing or analysis for the 1-way ANOVA framework for the iris data (<code>data(iris)</code>; <code>help(iris)</code>).</p>
<p><br></p>
</section>
</section>
<section id="harper-adams-data-science" class="level2">
<h2 class="anchored" data-anchor-id="harper-adams-data-science">Harper Adams Data Science</h2>
<p><img src="img/HDS.png" class="img-fluid" alt="Harper Data Science" width="125"></p>
<p>This website supports students and staff at <a href="https://www.harper-adams.ac.uk/" title="Harper Adams University">Harper Adams University</a> and the <a href="https://www.harper-adams.ac.uk/courses/postgraduate/201194/data-science-for-global-agriculture-food-and-environment" title="MSc in Data Science">MSc in Data Science for Global Agriculture, Food, and Environment</a> led by <a href="https://www.harper-adams.ac.uk/general/staff/profile/201620/Edwin-Harris/" title="Ed's Faculty page">Ed Harris</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>