project:
  type: website
  output-dir: docs

website:
  title: "R Stats Bootcamp"
  sidebar:
    logo: "img/rstats-logo.png"
    style: "docked"
    search: true
    contents: 
      - section: "Information"
        contents:
          - index.qmd
          - schedule.qmd
      - section: "Module 1: R"
        contents:
          - 1-setup.qmd
          - 2-r-lang.qmd
          - 3-functions.qmd
          - 4-data.qmd
          - 5-data-frames.qmd
          - 6-data-manipulation.qmd
      - section: "Module 2: Stats"
        contents:
          - 7-question-explore.qmd

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

