project:
  type: website
  output-dir: docs

website:
  favicon: "img/rstats-logo.png"
  title: "R Stats Bootcamp"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "About"
        file: about.qmd
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Getting Started"
        contents:
          - index.qmd
          - schedule.qmd
          - about.qmd
      - section: "Module 1: R Foundations"
        contents:
          - 01-setup.qmd
          - 02-r-lang.qmd
          - 03-functions.qmd
          - 04-data.qmd
          - 05-data-frames.qmd
          - 06-data-manipulation.qmd
      - section: "Module 2: Statistical Analysis"
        contents:
          - 07-question-explore.qmd
          - 08-sampling-dist.qmd
          - 09-correlation.qmd
          - 10-regression.qmd
          - 11-t-test.qmd
          - 12-1-way-anova.qmd
      - section: "Module 3: Reproducible Research"
        contents:
          - 13-reproducibility.qmd
          - 14-rmarkdown.qmd
          - 15-github-basics.qmd
          - 16-collaborative-workflows.qmd
  page-footer: 
    center: "© 2025 R Stats Bootcamp :: 🦑 [GitHub](https://github.com/your-repo/RStatsBootcamp-2025)"

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-link: true
    code-copy: true
    code-tools:
      source: false
      toggle: true
      caption: none

editor: source

