[build]
  publish = "_site"
  command = "quarto render"

[build.environment]
  QUARTO_VERSION = "1.7.30"

[[plugins]]
  package = "@netlify/plugin-quarto"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
