name: Build and Deploy Quarto Site with R

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("quarto", "rmarkdown", "tidyverse", "reshape2", "xml2", "downlit"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.30

      - name: Render the site
        run: quarto render

      - name: Deploy to Netlify branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: netlify-build
          folder: _site
