name: Build Quarto site for Netlify

on:
  push:
    branches:
      - main  # Or whatever your main branch is called

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "quarto", "rmarkdown"))'

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.30

      - name: Render site
        run: quarto render

      - name: Push built site to netlify-build branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: netlify-build
          folder: _site
          clean: true
